### ISSUE TITLE
Print functions need parenthesis

### ISSUE THREAD

**Issue by vikineema** [ArMoraer/dem-utils#1]
When running the ```dem_generator.py``` script using python 3 , it raises the error ```SyntaxError: Missing parentheses in call to 'print'. Did you mean print('')```.  

To reproduce the error run ```python dem_generator.py --width 2000 --height 2000 --waterratio 0.3 --island --preset mountainous_island dem.tif``` using Python 3.9.6.

**Comment by ArMoraer** [comment]
Thanks for your feedback. This issue is now fixed.
